# Generated by Django 3.2.19 on 2023-07-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'address')},
        ),
    ]
